### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by DeJure** [NCrusher74/SwiftTaggerMP4#13]
Hello,
I'm getting the following errors during the compilation: 

![photo_2021-08-27_20-16-33](https://user-images.githubusercontent.com/998982/131173671-f6bdacfe-1200-46d2-bb69-8303387c4d1c.jpg)

![photo_2021-08-27_20-32-44](https://user-images.githubusercontent.com/998982/131173691-d8f5ef9e-4999-4686-b590-0d83c201428d.jpg)

Xcode version 12.5.1

Can you suggest what I'm missing?
Thank you

**Comment by NCrusher74** [comment]
Hi, sorry for the delay in responding. Life has prevented me from working on this recently.

As to the first error, I suspect you need to update your dependencies. Likely I've made some change to `SwiftConvenienceExtensions`, as that is where `convertCamelToUpperCase` is found.

As to the second, I suspect fixing the first will resolve it, but if it doesn't, let me know.

**Comment by DeJure** [comment]
Hi,
No worries for the delay and thank you for getting back to me.
There should be something that I'm still not getting. You see, in the following commit https://github.com/NCrusher74/SwiftConvenienceExtensions/commit/1be5497d76f6c56e06baadfd0b667fa2e053cbf9 
both convertedCamelCase and convertCamelToUpperCase functions were substituted with the calculated properties titleCase and camelToUpperCase. Therefore, SwiftConvenienceExtensions 3.0.22 (the last committed and required by SwiftTaggerMP4 1.8.2) does not contain the necessary functions.

**Comment by NCrusher74** [comment]
Ah okay, I see what I did. I renamed/tweaked some of the extensions while working on SwiftTaggerID3, and didn't get a chance to check the changes out in SwiftTaggerMP4 before that life thing happened.

Update to SwiftTaggerMP4 1.8.3 and see if that solves the problem.
